begin;
create extension if not exists pgtap with schema extensions;
set search_path to public, extensions;
-- These calls formerly accepted scripted checkpoints without gameplay.
-- Assert both catalog privileges and actual execution under each API role.
select no_plan();
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at)
values ('20000000-0000-4000-8000-000000000001','00000000-0000-0000-0000-000000000000','authenticated','authenticated','rank-a@example.invalid','',now());
select ok((select relrowsecurity from pg_class where oid='public.ranked_runs'::regclass),'ranked RLS remains');
select ok((select relrowsecurity from pg_class where oid='public.ranked_events'::regclass),'event RLS remains');
select ok(not has_function_privilege('anon','public.start_ranked_run(text)','EXECUTE'),'anon: start_ranked_run revoked');
select ok(not has_function_privilege('anon','public.checkpoint_ranked_round(uuid,integer)','EXECUTE'),'anon: checkpoint_ranked_round revoked');
select ok(not has_function_privilege('anon','public.finish_ranked_run(uuid)','EXECUTE'),'anon: finish_ranked_run revoked');
select ok(not has_function_privilege('anon','public.start_ranked_run_v2(text,uuid)','EXECUTE'),'anon: start_ranked_run_v2 revoked');
select ok(not has_function_privilege('anon','public.checkpoint_ranked_round_v2(uuid,integer,integer,uuid)','EXECUTE'),'anon: checkpoint_ranked_round_v2 revoked');
select ok(not has_function_privilege('anon','public.finish_ranked_run_v2(uuid,integer)','EXECUTE'),'anon: finish_ranked_run_v2 revoked');
select ok(not has_function_privilege('anon','public.get_leaderboard(text,text,integer)','EXECUTE'),'anon: get_leaderboard revoked');
set local role anon;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.start_ranked_run('script')$$,'42501',null,'anon: start_ranked_run execution denied');
select throws_ok($$select public.checkpoint_ranked_round('10000000-0000-4000-8000-000000000001',1)$$,'42501',null,'anon: checkpoint_ranked_round execution denied');
select throws_ok($$select public.finish_ranked_run('10000000-0000-4000-8000-000000000001')$$,'42501',null,'anon: finish_ranked_run execution denied');
select throws_ok($$select public.start_ranked_run_v2('script','10000000-0000-4000-8000-000000000001')$$,'42501',null,'anon: start_ranked_run_v2 execution denied');
select throws_ok($$select public.checkpoint_ranked_round_v2('10000000-0000-4000-8000-000000000001',1,1,'30000000-0000-4000-8000-000000000001')$$,'42501',null,'anon: checkpoint_ranked_round_v2 execution denied');
select throws_ok($$select public.finish_ranked_run_v2('10000000-0000-4000-8000-000000000001',1)$$,'42501',null,'anon: finish_ranked_run_v2 execution denied');
select throws_ok($$select public.get_leaderboard('world',null,100)$$,'42501',null,'anon: get_leaderboard execution denied');
reset role;
select ok(not has_function_privilege('authenticated','public.start_ranked_run(text)','EXECUTE'),'authenticated: start_ranked_run revoked');
select ok(not has_function_privilege('authenticated','public.checkpoint_ranked_round(uuid,integer)','EXECUTE'),'authenticated: checkpoint_ranked_round revoked');
select ok(not has_function_privilege('authenticated','public.finish_ranked_run(uuid)','EXECUTE'),'authenticated: finish_ranked_run revoked');
select ok(not has_function_privilege('authenticated','public.start_ranked_run_v2(text,uuid)','EXECUTE'),'authenticated: start_ranked_run_v2 revoked');
select ok(not has_function_privilege('authenticated','public.checkpoint_ranked_round_v2(uuid,integer,integer,uuid)','EXECUTE'),'authenticated: checkpoint_ranked_round_v2 revoked');
select ok(not has_function_privilege('authenticated','public.finish_ranked_run_v2(uuid,integer)','EXECUTE'),'authenticated: finish_ranked_run_v2 revoked');
select ok(not has_function_privilege('authenticated','public.get_leaderboard(text,text,integer)','EXECUTE'),'authenticated: get_leaderboard revoked');
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.start_ranked_run('script')$$,'42501',null,'authenticated: start_ranked_run execution denied');
select throws_ok($$select public.checkpoint_ranked_round('10000000-0000-4000-8000-000000000001',1)$$,'42501',null,'authenticated: checkpoint_ranked_round execution denied');
select throws_ok($$select public.finish_ranked_run('10000000-0000-4000-8000-000000000001')$$,'42501',null,'authenticated: finish_ranked_run execution denied');
select throws_ok($$select public.start_ranked_run_v2('script','10000000-0000-4000-8000-000000000001')$$,'42501',null,'authenticated: start_ranked_run_v2 execution denied');
select throws_ok($$select public.checkpoint_ranked_round_v2('10000000-0000-4000-8000-000000000001',1,1,'30000000-0000-4000-8000-000000000001')$$,'42501',null,'authenticated: checkpoint_ranked_round_v2 execution denied');
select throws_ok($$select public.finish_ranked_run_v2('10000000-0000-4000-8000-000000000001',1)$$,'42501',null,'authenticated: finish_ranked_run_v2 execution denied');
select throws_ok($$select public.get_leaderboard('world',null,100)$$,'42501',null,'authenticated: get_leaderboard execution denied');
reset role;
select ok(not has_function_privilege('service_role','public.start_ranked_run(text)','EXECUTE'),'service_role: start_ranked_run revoked');
select ok(not has_function_privilege('service_role','public.checkpoint_ranked_round(uuid,integer)','EXECUTE'),'service_role: checkpoint_ranked_round revoked');
select ok(not has_function_privilege('service_role','public.finish_ranked_run(uuid)','EXECUTE'),'service_role: finish_ranked_run revoked');
select ok(not has_function_privilege('service_role','public.start_ranked_run_v2(text,uuid)','EXECUTE'),'service_role: start_ranked_run_v2 revoked');
select ok(not has_function_privilege('service_role','public.checkpoint_ranked_round_v2(uuid,integer,integer,uuid)','EXECUTE'),'service_role: checkpoint_ranked_round_v2 revoked');
select ok(not has_function_privilege('service_role','public.finish_ranked_run_v2(uuid,integer)','EXECUTE'),'service_role: finish_ranked_run_v2 revoked');
select ok(not has_function_privilege('service_role','public.get_leaderboard(text,text,integer)','EXECUTE'),'service_role: get_leaderboard revoked');
set local role service_role;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.start_ranked_run('script')$$,'42501',null,'service_role: start_ranked_run execution denied');
select throws_ok($$select public.checkpoint_ranked_round('10000000-0000-4000-8000-000000000001',1)$$,'42501',null,'service_role: checkpoint_ranked_round execution denied');
select throws_ok($$select public.finish_ranked_run('10000000-0000-4000-8000-000000000001')$$,'42501',null,'service_role: finish_ranked_run execution denied');
select throws_ok($$select public.start_ranked_run_v2('script','10000000-0000-4000-8000-000000000001')$$,'42501',null,'service_role: start_ranked_run_v2 execution denied');
select throws_ok($$select public.checkpoint_ranked_round_v2('10000000-0000-4000-8000-000000000001',1,1,'30000000-0000-4000-8000-000000000001')$$,'42501',null,'service_role: checkpoint_ranked_round_v2 execution denied');
select throws_ok($$select public.finish_ranked_run_v2('10000000-0000-4000-8000-000000000001',1)$$,'42501',null,'service_role: finish_ranked_run_v2 execution denied');
select throws_ok($$select public.get_leaderboard('world',null,100)$$,'42501',null,'service_role: get_leaderboard execution denied');
reset role;
select ok(not has_table_privilege('anon','public.ranked_runs','INSERT'),'anon: ranked_runs INSERT denied');
select ok(not has_table_privilege('anon','public.ranked_runs','UPDATE'),'anon: ranked_runs UPDATE denied');
select ok(not has_table_privilege('anon','public.ranked_runs','DELETE'),'anon: ranked_runs DELETE denied');
select ok(not has_table_privilege('anon','public.ranked_events','INSERT'),'anon: ranked_events INSERT denied');
select ok(not has_table_privilege('anon','public.ranked_events','UPDATE'),'anon: ranked_events UPDATE denied');
select ok(not has_table_privilege('anon','public.ranked_events','DELETE'),'anon: ranked_events DELETE denied');
select ok(not has_table_privilege('anon','public.wallet_ledger','INSERT'),'anon: wallet_ledger INSERT denied');
select ok(not has_table_privilege('anon','public.wallet_ledger','UPDATE'),'anon: wallet_ledger UPDATE denied');
select ok(not has_table_privilege('anon','public.wallet_ledger','DELETE'),'anon: wallet_ledger DELETE denied');
select ok(not has_table_privilege('anon','public.entitlements','INSERT'),'anon: entitlements INSERT denied');
select ok(not has_table_privilege('anon','public.entitlements','UPDATE'),'anon: entitlements UPDATE denied');
select ok(not has_table_privilege('anon','public.entitlements','DELETE'),'anon: entitlements DELETE denied');
select ok(not has_table_privilege('anon','public.store_transactions','INSERT'),'anon: store_transactions INSERT denied');
select ok(not has_table_privilege('anon','public.store_transactions','UPDATE'),'anon: store_transactions UPDATE denied');
select ok(not has_table_privilege('anon','public.store_transactions','DELETE'),'anon: store_transactions DELETE denied');
select ok(not has_table_privilege('authenticated','public.ranked_runs','INSERT'),'authenticated: ranked_runs INSERT denied');
select ok(not has_table_privilege('authenticated','public.ranked_runs','UPDATE'),'authenticated: ranked_runs UPDATE denied');
select ok(not has_table_privilege('authenticated','public.ranked_runs','DELETE'),'authenticated: ranked_runs DELETE denied');
select ok(not has_table_privilege('authenticated','public.ranked_events','INSERT'),'authenticated: ranked_events INSERT denied');
select ok(not has_table_privilege('authenticated','public.ranked_events','UPDATE'),'authenticated: ranked_events UPDATE denied');
select ok(not has_table_privilege('authenticated','public.ranked_events','DELETE'),'authenticated: ranked_events DELETE denied');
select ok(not has_table_privilege('authenticated','public.wallet_ledger','INSERT'),'authenticated: wallet_ledger INSERT denied');
select ok(not has_table_privilege('authenticated','public.wallet_ledger','UPDATE'),'authenticated: wallet_ledger UPDATE denied');
select ok(not has_table_privilege('authenticated','public.wallet_ledger','DELETE'),'authenticated: wallet_ledger DELETE denied');
select ok(not has_table_privilege('authenticated','public.entitlements','INSERT'),'authenticated: entitlements INSERT denied');
select ok(not has_table_privilege('authenticated','public.entitlements','UPDATE'),'authenticated: entitlements UPDATE denied');
select ok(not has_table_privilege('authenticated','public.entitlements','DELETE'),'authenticated: entitlements DELETE denied');
select ok(not has_table_privilege('authenticated','public.store_transactions','INSERT'),'authenticated: store_transactions INSERT denied');
select ok(not has_table_privilege('authenticated','public.store_transactions','UPDATE'),'authenticated: store_transactions UPDATE denied');
select ok(not has_table_privilege('authenticated','public.store_transactions','DELETE'),'authenticated: store_transactions DELETE denied');
select is((select count(*) from public.ranked_runs),0::bigint,'scripted RPC attempts created no runs');
select is((select count(*) from public.ranked_events),0::bigint,'scripted RPC attempts created no events');
select ok(not has_table_privilege('authenticated','public.store_transactions','SELECT'),'store evidence stays private');
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
select lives_ok($$select public.set_player_profile('Pilot A','us')$$,'non-ranked profile remains usable');
select throws_ok($$insert into public.entitlements(user_id,entitlement_key,source) values ('20000000-0000-4000-8000-000000000001','premium','forged')$$,'42501',null,'direct entitlement forgery denied');
reset role;
select * from finish();
rollback;
